apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitea
  namespace: smol-devtools
spec:
  interval: 5m
  url: https://dl.gitea.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: smol-devtools
spec:
  releaseName: gitea
  targetNamespace: smol-devtools
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea
  values:
    gitea:
      config:
        database:
          DB_TYPE: postgres
      additionalConfigFromEnvs:
      - name: ENV_TO_INI__DATABASE__HOST
        valueFrom:
          secretKeyRef:
            name: postgres-gitea-role-secret
            key: endpoint
      - name: ENV_TO_INI__DATABASE__NAME
        value: gitea
      - name: ENV_TO_INI__DATABASE__USER
        valueFrom:
          secretKeyRef:
            name: postgres-gitea-role-secret
            key: username
      - name: ENV_TO_INI__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            name: postgres-gitea-role-secret
            key: password
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    memcached:
      enabled: false
    postgresql:
      enabled: false
    mysql:
      enabled: false
    mariadb:
      enabled: false
    ingress:
      enabled: true
      hosts:
        - host: git.k8s.lan
          paths:
            - path: /
              pathType: Prefix
  interval: 1m
  install:
    remediation:
      retries: 3
