---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins
  namespace: smol-devtools
spec:
  interval: 1h0m0s
  path: ./deploy/jenkins
  prune: true
  sourceRef:
    kind: GitRepository
    name: smol-devtools
  validation: client
