apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jenkins
  namespace: smol-devtools
spec:
  interval: 5m
  url: https://charts.jenkins.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: smol-devtools
spec:
  releaseName: jenkins
  targetNamespace: smol-devtools
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
  values:
    controller:
      image:
        registry: harbor.k8s.lan
        repository: smol/jenkins
        tag: lts
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
          ephemeral-storage: 64Mi
        limits:
          cpu: 500m
          memory: 1Gi
          ephemeral-storage: 64Mi
      ingress:
        enabled: true
        paths: []
        apiVersion: networking.k8s.io/v1
        hostName: jenkins.k8s.lan
  interval: 1m
  install:
    remediation:
      retries: 3
