apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: renovate
  namespace: smol-devtools
spec:
  interval: 5m
  url: https://docs.renovatebot.com/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: smol-devtools
spec:
  releaseName: renovate
  targetNamespace: smol-devtools
  chart:
    spec:
      chart: renovate
      sourceRef:
        kind: HelmRepository
        name: renovate
  values:
    cronjob:
      concurrencyPolicy: 'Forbid'
      schedule: '@daily'
    existingSecret: renovate-env
    renovate:
      config: '{ "rebaseWhen": "behind-base-branch" }'
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 250m
        memory: 1Gi
  interval: 1m
  install:
    remediation:
      retries: 3
